server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: mysql://b8875c88c31cf7:b6933a6a@us-cdbr-east-06.cleardb.net/heroku_a9f78cbacba7331?reconnect=true
    username: b8875c88c31cf7
    password: b6933a6a
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        ddl-auto: create
    generate-ddl: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: wndmsdl0920@gmail.com
    password: [ smtp password ]
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: ${AWS_BUCKET_NAME}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false



logging:
  file:
    name: logs/application-debug.log
  pattern:
    file: "%d %-5level [%thread] &logger : %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 10
  level:
    root: info
    com.esca.escahp: debug
